Entity/PostInterface.php
<?php
/**
 * Copyright (c) 2019 Aleksander Winter <aleksander.winter.89@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */

namespace SonOfLiberty\NewsBundle\Entity;

/**
 * Interface PostInterface
 * @package SonOfLiberty\NewsBundle\Entity
 */
interface PostInterface
{
    /**
     * @return string|null
     */
    public function getTitle(): ?string;

    /**
     * @return string|null
     */
    public function getContent(): ?string;
}

Resources/views/post_detail.html.twig
<p>
    <a href="{{ path('son_of_liberty_news_list_posts') }}">
        {{ 'layout.back_to_list'|trans({}, 'SonOfLibertyNewsBundle') }}
    </a>
</p>

<article>
    <h1>{{ post.title }}</h1>
    <p>{{ post.content|raw}}</p>
</article>

Resources/views/post_list.html.twig
<ul>
    {% for post in posts %}
        <li>
            <a href="{{ path('son_of_liberty_news_get_post', {'slug': post.slug}) }}">
                {{ post.title }}
            </a>
        </li>
    {% endfor %}
</ul>

{{ knp_pagination_render(posts) }}